config/routes.rb
Rails.application.routes.draw do

  resources :special_holidays
  resources :special_holiday_ctgrs
  resources :extra_holidays

  root 'static_pages#home'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :timecards do
    member do
      post 'workflow'
      post 'apply_all'
      post 'approve_all'
    end
  end
  get 'paid_holidays' => 'paid_holidays#index'
  resources :reports
  get 'report_download' => 'report_submissions#download'
  get 'my_reports' => 'reports#my_reports'
  resources :report_submissions do
    member do
      post 'approve'
    end
  end
  resources :users

end

app/models/timecard.rb
# == Schema Information
#
# Table name: timecards
#
#  id                 :integer          not null, primary key
#  biz_date           :date
#  attn_ctgr          :integer
#  work_start_time    :datetime
#  work_end_time      :datetime
#  rest_start_time    :datetime
#  rest_end_time      :datetime
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  user_id            :integer
#  wf_status          :integer          default(0)
#  paid_holiday_hours :integer          default(0)
#

class Timecard < ActiveRecord::Base
  VALID_TIME_REGEX = /\A(\d{1,2}):(\d{2})\z/
  validates :work_start_time, presence: true
  validates :work_end_time, presence: true
  validates :rest_start_time, presence: true
  validates :rest_end_time, presence: true
  validates_numericality_of :paid_holiday_hours, less_than: 9
  validate :check_time_relation
  validate :check_paid_holiday
  validate :check_holiday_work

  attr_accessor :is_new, :is_editable, :attn_ctgr_disp, :holiday_ctgr, :wf_status_ctgr_disp, 
                :remaining_paid_days, :remaining_paid_hours
  # holiday_ctgr 0:non-holiday 1:holiday 2:Sadurday 3:Sunday

  def check_time_relation
    return if self.wf_status == 0

    unless self.work_start_time <= self.rest_start_time && self.rest_start_time <= self.rest_end_time && self.rest_end_time <= self.work_end_time
      errors[:base] << "時間の前後関係が不正です"
    end
  end

  def check_paid_holiday
    self.paid_holiday_hours = 0 if self.attn_ctgr != 0

    return if self.attn_ctgr != 2 && self.paid_holiday_hours == 0

    if self.attn_ctgr == 2 && self.remaining_paid_days.to_i == 0
      errors[:attn_ctgr] << "残有給休暇日数が足りません"
    end

    if self.paid_holiday_hours && (self.remaining_paid_hours.to_i <  self.paid_holiday_hours)
      errors[:paid_holiday_hours] << "残有給休暇時間が足りません"
    end
  end

  def check_holiday_work
    if Timecard.get_holiday_ctgr(self.biz_date) != 0
      if self.attn_ctgr == 1 || self.attn_ctgr == 2
        self.attn_ctgr = 9
      end
    end
  end

  def modify_times_date
    self.work_start_time = Time.zone.local(biz_date.year, biz_date.month, biz_date.day,
                                           self.work_start_time.hour, self.work_start_time.min, 0)
    self.work_end_time = Time.zone.local(biz_date.year, biz_date.month, biz_date.day,
                                           self.work_end_time.hour, self.work_end_time.min, 0)
    self.rest_start_time = Time.zone.local(biz_date.year, biz_date.month, biz_date.day,
                                           self.rest_start_time.hour, self.rest_start_time.min, 0)
    self.rest_end_time = Time.zone.local(biz_date.year, biz_date.month, biz_date.day,
                                           self.rest_end_time.hour, self.rest_end_time.min, 0)
  end

  def self.get_holiday_ctgr(date)
    if HolidayJapan.check(date)
      return 1
    elsif date.wday == 0
      return 3
    elsif date.wday == 6
      return 2
    else
      return 0
    end
  end
end

app/controllers/timecards_controller.rb
class TimecardsController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :create, :update]

  def index
    if params[:year] == nil
      @b_date = Date.today.beginning_of_month
    else
      @b_date = Date.new(params[:year].to_i, params[:month].to_i, 1)
    end
    e_date = @b_date.end_of_month

    if params[:user] == nil
      user_id = current_user.id
    else
      user_id = params[:user].to_i
    end
    @user = User.find(user_id)

    if @user.use_def_times
      def_work_start_time = @user.def_work_start_time || Date.today.to_time
      def_work_end_time = @user.def_work_end_time || Date.today.to_time
      def_rest_start_time = @user.def_rest_start_time || Date.today.to_time
      def_rest_end_time = @user.def_rest_end_time || Date.today.to_time
    else
      def_work_start_time = Date.today.to_time
      def_work_end_time = Date.today.to_time
      def_rest_start_time = Date.today.to_time
      def_rest_end_time = Date.today.to_time
    end
    @biz_days = 0
    @attn_days = 0
    @absc_days = 0
    @paid_days = 0
    @paid_hours = 0
    @work_mins = 0
    work_mins_a = 0 # 00:00-04:59 0-
    work_mins_b = 0 # 05:00-09:29 300-
    work_mins_c = 0 # 09:30-18:29 570-
    work_mins_d = 0 # 18:30-21:59 1110-
    work_mins_e = 0 # 22:00-23:59 1320-
    @work_mins_holiday = 0
    attn_ctgrs = Category.where("ctgr_id = ? and lang_id = ?", 0, 0)
    wf_status_ctgr = Category.where("ctgr_id = ? and lang_id = ?", 1, 0)
    timecards = Timecard.where(biz_date: @b_date..e_date).where(user_id: user_id)
    @monthly_timecards = Array.new
    (@b_date..e_date).each do |date|
      if timecards.exists?(biz_date: date)
        tc = timecards.find_by(biz_date: date)
        tc.is_new = false
        tc.holiday_ctgr = Timecard.get_holiday_ctgr(tc.biz_date)

        if tc.wf_status >= 5
          if tc.attn_ctgr == 0
            @attn_days += 1
            @paid_hours += tc.paid_holiday_hours
            @work_mins += (tc.work_end_time - tc.work_start_time).div(60)
            @work_mins -= (tc.rest_end_time - tc.rest_start_time).div(60)

            if tc.holiday_ctgr == 0
              work_start_index = tc.work_start_time.hour * 60 + tc.work_start_time.min
              rest_start_index = tc.rest_start_time.hour * 60 + tc.rest_start_time.min
              rest_end_index = tc.rest_end_time.hour * 60 + tc.rest_end_time.min
              work_end_index = tc.work_end_time.hour * 60 + tc.work_end_time.min
              work_blocks = []
              1440.times do |i|
                if i < work_start_index
                  work_blocks.push 0
                elsif i < rest_start_index
                  work_blocks.push 1
                elsif i < rest_end_index
                  work_blocks.push 0
                elsif i < work_end_index
                  work_blocks.push 1
                else
                  work_blocks.push 0
                end
              end
              work_mins_a += work_blocks[0...300].inject(:+) # 00:00-04:59 0-
              work_mins_b += work_blocks[300...570].inject(:+) # 05:00-09:29 300-
              work_mins_c += work_blocks[570...1110].inject(:+) # 09:30-18:29 570-
              work_mins_d += work_blocks[1110...1320].inject(:+) # 18:30-21:59 1110-
              work_mins_e += work_blocks[1320...1440].inject(:+) # 22:00-23:59 1320-
            else
              @work_mins_holiday += (tc.work_end_time - tc.work_start_time).div(60)
              @work_mins_holiday -= (tc.rest_end_time - tc.rest_start_time).div(60)
            end
          elsif tc.attn_ctgr == 2
            @paid_days += 1
          end
        end
      else
        tc = Timecard.new
        tc.biz_date = date
        tc.work_start_time = sum_date_time(date, def_work_start_time)
        tc.work_end_time = sum_date_time(date, def_work_end_time)
        tc.rest_start_time = sum_date_time(date, def_rest_start_time)
        tc.rest_end_time = sum_date_time(date, def_rest_end_time)
        tc.id = 999
        tc.is_new = true
        tc.holiday_ctgr = Timecard.get_holiday_ctgr(tc.biz_date)
        if tc.holiday_ctgr == 0
          tc.attn_ctgr = 0
        else
          tc.attn_ctgr = 9
        end
      end

      if tc.holiday_ctgr == 0
        @biz_days += 1
        @absc_days += 1 if (tc.attn_ctgr == 1) && (tc.wf_status >= 5)
      end

      tc.attn_ctgr_disp = attn_ctgrs.find_by(val: tc.attn_ctgr).name
      tc.wf_status_ctgr_disp = wf_status_ctgr.find_by(val: tc.wf_status).name

      @monthly_timecards[@monthly_timecards.length] = tc
    end
    @work_mins_normal = work_mins_c
    @work_mins_over   = work_mins_b + work_mins_d
    @work_mins_night  = work_mins_a + work_mins_e
    @my_applicants = Approver.where(approver_user_id: current_user.id).where.not(user_id: current_user.id)
    my_group_ids = GroupMember.where(user_id: current_user.id).pluck(:group_id)
    @my_group_members = GroupMember.where(group_id: my_group_ids).where.not(user_id: current_user.id)
  end

  def show
  end

  def new
    biz_date = Date.parse(params[:biz_date])
    user = User.find(params[:user])
    if user.use_def_times
      def_work_start_time = sum_date_time(biz_date, user.def_work_start_time)
      def_work_end_time = sum_date_time(biz_date, user.def_work_end_time)
      def_rest_start_time = sum_date_time(biz_date, user.def_rest_start_time)
      def_rest_end_time = sum_date_time(biz_date, user.def_rest_end_time)
    else
      def_work_start_time = biz_date.to_time
      def_work_end_time = biz_date.to_time
      def_rest_start_time = biz_date.to_time
      def_rest_end_time = biz_date.to_time
    end
    @timecard = Timecard.new(biz_date: biz_date, attn_ctgr: 0,
                             work_start_time: def_work_start_time,
                             work_end_time: def_work_end_time,
                             rest_start_time: def_rest_start_time,
                             rest_end_time: def_rest_end_time,
                             user_id: params[:user].to_i)

    if editable?(@timecard)
      remaining_paid_holidays = remaining_paid_holidays(@timecard.biz_date, @timecard.user_id)
      @timecard.remaining_paid_days = remaining_paid_holidays[0].to_i
      @timecard.remaining_paid_hours = remaining_paid_holidays[1].to_i
      render 'edit'
    else
      render 'show'
    end
  end

  def edit
    @timecard = Timecard.find(params[:id])

    remaining_paid_holidays = remaining_paid_holidays(@timecard.biz_date, @timecard.user_id)
    @timecard.remaining_paid_days = remaining_paid_holidays[0].to_i
    @timecard.remaining_paid_hours = remaining_paid_holidays[1].to_i
    if @timecard.attn_ctgr == 2
      @timecard.remaining_paid_days += 1
    elsif @timecard.paid_holiday_hours > 0
      @timecard.remaining_paid_hours += @timecard.paid_holiday_hours
    end

    render 'show' if !editable?(@timecard)
  end

  def create
    @timecard = Timecard.new(timecard_params)
    @timecard.modify_times_date
    if params[:submit]
      @timecard.wf_status = 5
    end

#    if @timecard.attn_ctgr != 0
#      @timecard.paid_holiday_hours = 0
#    end

    if @timecard.save
      if @timecard.attn_ctgr == 2
        use_paid_holiday(@timecard.user_id, @timecard.biz_date, 1, 0)
      elsif @timecard.attn_ctgr == 0 && @timecard.paid_holiday_hours > 0
        use_paid_holiday(@timecard.user_id, @timecard.biz_date, 0, @timecard.paid_holiday_hours)
      end

      flash[:success] = "Timecard updated!"
      redirect_to timecards_path(user: @timecard.user_id,
                                 year: @timecard.biz_date.year, month: @timecard.biz_date.month)
    else
      remaining_paid_holidays = remaining_paid_holidays(@timecard.biz_date, @timecard.user_id)
      @timecard.remaining_paid_days = remaining_paid_holidays[0].to_i
      @timecard.remaining_paid_hours = remaining_paid_holidays[1].to_i
      render 'edit'
    end
  end

  def update
    @timecard = Timecard.find(params[:id])
    if params[:save]
      @timecard.wf_status = 0
    elsif params[:submit]
      @timecard.wf_status = 5
    elsif params[:approve] && view_context.approver_of?(@timecard.user_id)
      @timecard.wf_status = 9
    end

    if @timecard.update_attributes(timecard_params)
      @timecard.modify_times_date

      if @timecard.attn_ctgr == 2
        use_paid_holiday(@timecard.user_id, @timecard.biz_date, 1, 0)
      elsif @timecard.attn_ctgr == 0 && @timecard.paid_holiday_hours > 0
        use_paid_holiday(@timecard.user_id, @timecard.biz_date, 0, @timecard.paid_holiday_hours)
      else
        PaidHolidayUsage.delete_all(["user_id = ? and usage_date = ?", @timecard.user_id, @timecard.biz_date])
      end

#      if @timecard.attn_ctgr != 0
#        @timecard.paid_holiday_hours = 0
#      end

      @timecard.save
      flash[:success] = "Timecard updated!"
      redirect_to timecards_path(user: @timecard.user_id,
                                 year: @timecard.biz_date.year, month: @timecard.biz_date.month)
    else
      remaining_paid_holidays = remaining_paid_holidays(@timecard.biz_date, @timecard.user_id)
      @timecard.remaining_paid_days = remaining_paid_holidays[0].to_i
      @timecard.remaining_paid_hours = remaining_paid_holidays[1].to_i
      render 'edit'
    end
  end

  def workflow # 2:Sent back 9:Approved
    timecard_id = params[:timecard][:id].to_i
    user_id = params[:timecard][:user].to_i
    wf_status = params[:timecard][:wf].to_i

    if wf_status == 2 || wf_status == 9
      @timecard = Timecard.find(timecard_id)
      @timecard.update_attribute(:wf_status, wf_status) if view_context.approver_of?(user_id)
    end

    redirect_to timecards_path(user: @timecard.user_id,
                               year: @timecard.biz_date.year, month: @timecard.biz_date.month)
  end

  def apply_all
    user = User.find(params[:id])
    if user.use_def_times
      def_work_start_time = user.def_work_start_time || Date.today.to_time
      def_work_end_time   = user.def_work_end_time || Date.today.to_time

app/helpers/timecards_helper.rb
module TimecardsHelper
  def approver_of?(user_id)
    Approver.where(user_id: user_id).where(approver_user_id: current_user.id).count > 0
  end
end

app/views/timecards/index.html.erb
<% provide(:title, '勤怠一覧') %>

<div class="row">
<div class="col-md-2 side-menu-member">
  <div class="panel panel-default panel-member" style="margin-top: 30px;">
    <ul class="nav nav-pills nav-stacked nav-member">
      <li <%= 'class="active"'.html_safe if @user.id == current_user.id  %>>
          <%= link_to timecards_path(user: current_user.id, year: @b_date.year, month: @b_date.month) do %>
            <span class="glyphicon glyphicon-user"></span>
            <%= current_user.name %>
          <% end %>
      </li>

      <% if current_user.is_secretary? %>
        <hr style="margin: 2px 10px;">
        <% User.where(admin: false).where.not(id: current_user.id).each do |u| %>
          <li <%= 'class="active"'.html_safe if u.id == @user.id %>>
            <%= link_to timecards_path(user: u.id, year: @b_date.year, month: @b_date.month) do %>
              <span class="glyphicon glyphicon-user"></span>
              <%= User.find(u).name %>
            <% end %>
          </li>
        <% end %>
      <% end %>

      <hr style="margin: 2px 10px;">
      <% @my_applicants.each do |ap| %>
        <li <%= 'class="active"'.html_safe if ap.user_id == @user.id  %>>
          <%= link_to timecards_path(user: ap.user_id, year: @b_date.year, month: @b_date.month) do %>
            <span class="glyphicon glyphicon-leaf"></span>
            <%= User.find(ap.user_id).name %>
            <% applied_count = Timecard.where(user_id: ap.user_id).where(wf_status: 5).count %>
            <% if applied_count > 0 %>
              <span class="badge pull-right"><%= applied_count %></span>
            <% end %>
          <% end %>
        </li>
      <% end %>
      <hr style="margin: 2px 10px;">
      <% @my_group_members.each do |gm| %>
        <li <%= 'class="active"'.html_safe if gm.user_id == @user.id  %>>
          <%= link_to timecards_path(user: gm.user_id, year: @b_date.year, month: @b_date.month) do %>
            <span class="glyphicon glyphicon-tree-deciduous"></span>
            <%= User.find(gm.user_id).name %>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

<div class="col-md-10">

<h1><%= @b_date.year %>年<%= @b_date.month %>月</h1>

<div class="center">
  <span class = "btn-group">
    <%= link_to "<<", timecards_path(user: @user.id, year: @b_date.year-1, month: 12),
                      class: "btn btn-default" %>
    <% (1..12).each do |i| %>
      <% if i == @b_date.month %>
        <%= link_to @b_date.year.to_s + "/" + i.to_s, 
            timecards_path(user: @user.id, year: @b_date.year, month: i), class: "btn btn-default active" %>
      <% else %>
        <%= link_to @b_date.year.to_s + "/" + i.to_s, 
            timecards_path(user: @user.id, year: @b_date.year, month: i), class: "btn btn-default" %>
      <% end %>
    <% end %>
    <%= link_to ">>", timecards_path(user: @user.id, year: @b_date.year+1, month: 1),
                      class: "btn btn-default" %>
  </span>
</div>

<br>

<table class="table table-bordered table-condensed">
  <thead>
    <tr align="center">
      <th class="centerized">営業日数</th>
      <th class="centerized">出勤日数</th>
      <th class="centerized">有給休暇</th>
      <th class="centerized">休暇日数</th>
      <th class="centerized">実労働時間</th>
    </tr>
  </thead>
  <tbody>
    <tr align="center">
      <th class="centerized"><%= @biz_days.to_s + " 日" %></th>
      <th class="centerized"><%= @attn_days.to_s + " 日" %></th>
      <th class="centerized"><%= @paid_days.to_s + " 日 / " + @paid_hours.to_s + " 時間"%></th>
      <th class="centerized"><%= @absc_days.to_s + " 日" %></th>
      <% work_hours = @work_mins.divmod(60) %>
      <% if work_hours[0] > 240 %>
        <% color_red = 'style="color: red;"' %>
      <% else %>
        <% color_red = '' %>
      <% end %>
      <th class="centerized" <%= color_red.html_safe %>>

        <div class="dropdown">
          <button class="btn btn-default btn-xs" type="button" id="work-breakdown-btn" data-toggle="dropdown">
            <strong><%= work_hours[0].to_s + " 時間 " + "%02d" % work_hours[1] + " 分" %></strong>
          </button>
          <ul class="dropdown-menu work-breakdown" aria-labelledby="work-breakdown-btn">
            <table style="width:100%;">
              <tr align="center">
                <% work_hours_normal = @work_mins_normal.divmod(60) %>
                <th>通常</th>
                <td><%= work_hours_normal[0].to_s + " 時間 " + "%02d" % work_hours_normal[1] + " 分" %></td>
              </tr>
              <tr align="center">
                <% work_hours_over = @work_mins_over.divmod(60) %>
                <th>時間外</th>
                <td><%= work_hours_over[0].to_s + " 時間 " + "%02d" % work_hours_over[1] + " 分" %></td>
              </tr>
              <tr align="center">
                <% work_hours_night = @work_mins_night.divmod(60) %>
                <th>深夜</th>
                <td><%= work_hours_night[0].to_s + " 時間 " + "%02d" % work_hours_night[1] + " 分" %></td>
              </tr>
              <tr align="center">
                <% work_hours_holiday = @work_mins_holiday.divmod(60) %>
                <th>休日</th>
                <td><%= work_hours_holiday[0].to_s + " 時間 " + "%02d" % work_hours_holiday[1] + " 分" %></td>
              </tr>
            </table>
          </ul>
        </div>
      </th>
    </tr>
  </tbody>
</table>

<table class="table table-hover">
  <thead>
    <tr align="center">
      <th class="centerized" colspan="2" rowspan="2">日付</th>
      <th class="centerized" rowspan="2">勤怠</th>
      <th class="centerized" colspan="2">業務</th>
      <th class="centerized" colspan="2">休憩</th>
      <th class="centerized" rowspan="2">有給休暇<br>（時間）</th>
      <th class="centerized col-md-2" rowspan="">
        <% if @user.id == current_user.id %>
          <%= button_to 'まとめて提出', apply_all_timecard_path(@user.id),
                        data: {confirm: 'まとめて提出しますか？'},
                        params: {apply_all_target_dates_form: '', year: @b_date.year, month: @b_date.month},
                        id: 'apply-all', class: 'btn btn-default btn-xs', style: 'width:90px;height:18px;' %>
        <% elsif approver_of?(@user.id)%>
          <%= button_to 'まとめて承認', approve_all_timecard_path(@user.id),
                        data: {confirm: 'まとめて承認しますか？'},
                        params: {approve_all_target_ids_form: '', year: @b_date.year, month: @b_date.month},
                        id: 'approve-all', class: 'btn btn-default btn-xs', style: 'width:90px;height:18px;' %>
        <% end %>
      </th>
    </tr>
    <tr align="center">
      <th class="centerized">開始</th>
      <th class="centerized">終了</th>
      <th class="centerized">開始</th>
      <th class="centerized">終了</th>
      <th class="centerized">ステータス</th>
    </tr>
  </thead>

  <tbody>
    <% biz_days = 0 %> <!-- 営業日数 -->
    <% work_days = 0 %><!-- 勤務日数 -->
    <% off_days = 0 %><!-- 休暇日数 -->
    <% work_mins = 0 %><!-- 勤務時間 -->
    <% apply_all_target_dates = [] %><!-- 一括申請の対象日付 -->
    <% approve_all_target_ids = [] %><!-- 一括承認の対象id -->
    <% @monthly_timecards.each do |tc| %>
      <% if tc.is_new %>
        <% data_link = new_timecard_path(biz_date: tc.biz_date, user: @user.id) %>
      <% else %>
        <% data_link = edit_timecard_path(tc) %>
      <% end %>

      <% bgcolor = '' %>
      <% wday_color_class = '' %>
      <% attn_ctgr_color = '' %>
      <% if tc.holiday_ctgr == 1 || tc.holiday_ctgr == 3 %>
        <% bgcolor = 'bgcolor="#a9a9a9"' %>
        <% wday_color_class = 'text-danger' %>
      <% elsif tc.holiday_ctgr == 2 %>
        <% bgcolor = 'bgcolor="#a9a9a9"' %>
        <% wday_color_class = 'text-primary'%>
      <% elsif tc.holiday_ctgr == 0 %>
        <% if tc.biz_date == Date.today %>
          <% bgcolor = 'bgcolor="#FFFFDD"' %>
        <% end %>
        <% if tc.attn_ctgr == 1 || tc.attn_ctgr == 2 %>
          <% attn_ctgr_color = 'style="color:red;"' %>
        <% end %>
      <% end %>

      <% wf_status_color = '' %>
      <% if (tc.wf_status == 0 || tc.wf_status == 2) && tc.biz_date < Date.today %>
        <% wf_status_color = 'style="color:red;"' %>
        <% apply_all_target_dates << tc.biz_date if tc.holiday_ctgr == 0 || tc.attn_ctgr == 0 %>
      <% elsif tc.wf_status == 5 %>
        <% wf_status_color = 'style="color:blue;"' %>
        <% approve_all_target_ids << tc.id %>
      <% elsif tc.wf_status == 9 %>
        <% wf_status_color = 'style="color:silver"' %>
      <% end %>

        <tr data-link="<%= data_link %>" style="cursor: pointer;" <%= bgcolor.html_safe %>>
          <td class="centerized"><%= tc.biz_date.to_s(:y_slash_m_slash_d) %></td>
          <td class="centerized <%= wday_color_class.html_safe %>">
            <% if tc.holiday_ctgr == 1 %>
              <%= HolidayJapan.name(tc.biz_date) %>
            <% else %>
              <%= l tc.biz_date, format: :day_name %>
            <% end %>
          </td>
          <td class="centerized" <%= attn_ctgr_color.html_safe %> ><%= tc.attn_ctgr_disp %></td>
          <% if tc.attn_ctgr == 0 %>
            <td class="centerized"><%= tc.work_start_time.to_s(:h_colon_m) %></td>
            <td class="centerized"><%= tc.work_end_time.to_s(:h_colon_m) %></td>
            <td class="centerized"><%= tc.rest_start_time.to_s(:h_colon_m) %></td>
            <td class="centerized"><%= tc.rest_end_time.to_s(:h_colon_m) %></td>
            <td class="centerized"><%= tc.paid_holiday_hours %></td>
          <% else %>
            <td class="centerized"></td>
            <td class="centerized"></td>
            <td class="centerized"></td>
            <td class="centerized"></td>
            <td class="centerized"></td>
          <% end %>
          <% if tc.attn_ctgr == 9 %>
            <td class="centerized"></td>
          <% else %>
            <td class="centerized" <%= wf_status_color.html_safe %>><%= tc.wf_status_ctgr_disp %></td>
          <% end %>
        </tr>
      <% end %>
  </tbody>
</table>

<%= hidden_field_tag 'apply_all_target_dates', apply_all_target_dates %>
<%= hidden_field_tag 'approve_all_target_ids', approve_all_target_ids %>

</div>

<script>
  $("tr[data-link]").click(function() {
    window.location = $(this).data("link")
  })

  // 固定する場所が存在することの確認
  if( $('.side-menu-member .panel-member').length > 0 ){
    var baseSelector = '.side-menu-member'
    var fixingSelector = baseSelector + ' .panel-member'

    $(window).on('load scroll resize', function(){
      //var baseTop = $(baseSelector).offset().top

      //固定開始位置より後にスクロールされた場合
      if( $(window).scrollTop() > 30 ){
        $(fixingSelector).addClass('fixed')
        $(baseSelector).height($(fixingSelector).outerHeight())
        $(fixingSelector).width($(baseSelector).width()-2)

       // if( $(window).scrollTop() > 500 ){
       //   $(fixingSelector).removeClass('fixed')
       //   $(fixingSelector).css('margin-top','500px')
       //   $(fixingSelector).width('')
       // }

      //固定開始位置以前にスクロールされた場合
      } else {
        $(fixingSelector).removeClass('fixed')
        $(baseSelector).height('')
        $(fixingSelector).width('')
      }
    })
  }

  $('#apply-all').click(function() {
    $('[name="apply_all_target_dates_form"]').val($('#apply_all_target_dates').val())
  })
  $('#approve-all').click(function() {
    $('[name="approve_all_target_ids_form"]').val($('#approve_all_target_ids').val())
  })
</script>