config/routes.rb
Rails.application.routes.draw do

  resources :special_holidays
  resources :special_holiday_ctgrs
  resources :extra_holidays

  root 'static_pages#home'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :timecards do
    member do
      post 'workflow'
      post 'apply_all'
      post 'approve_all'
    end
  end
  get 'paid_holidays' => 'paid_holidays#index'
  resources :reports
  get 'report_download' => 'report_submissions#download'
  get 'my_reports' => 'reports#my_reports'
  resources :report_submissions do
    member do
      post 'approve'
    end
  end
  resources :users

end

app/models/extra_holiday.rb
# == Schema Information
#
# Table name: extra_holidays
#
#  id                  :integer          not null, primary key
#  title               :string
#  description         :string
#  is_hourly           :boolean
#  is_comment_required :boolean
#  is_paid             :boolean
#  is_as_attended      :boolean
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#

class ExtraHoliday < ActiveRecord::Base
end

app/controllers/extra_holidays_controller.rb
class ExtraHolidaysController < ApplicationController
  before_action :require_admin
  before_action :set_extra_holiday, only: [:show, :edit, :update, :destroy]

  # GET /extra_holidays
  # GET /extra_holidays.json
  def index
    @extra_holidays = ExtraHoliday.all
  end

  # GET /extra_holidays/1
  # GET /extra_holidays/1.json
  def show
  end

  # GET /extra_holidays/new
  def new
    @extra_holiday = ExtraHoliday.new
  end

  # GET /extra_holidays/1/edit
  def edit
  end

  # POST /extra_holidays
  # POST /extra_holidays.json
  def create
    @extra_holiday = ExtraHoliday.new(extra_holiday_params)

    respond_to do |format|
      if @extra_holiday.save
        format.html { redirect_to @extra_holiday, notice: 'Extra holiday was successfully created.' }
        format.json { render :show, status: :created, location: @extra_holiday }
      else
        format.html { render :new }
        format.json { render json: @extra_holiday.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /extra_holidays/1
  # PATCH/PUT /extra_holidays/1.json
  def update
    respond_to do |format|
      if @extra_holiday.update(extra_holiday_params)
        format.html { redirect_to @extra_holiday, notice: 'Extra holiday was successfully updated.' }
        format.json { render :show, status: :ok, location: @extra_holiday }
      else
        format.html { render :edit }
        format.json { render json: @extra_holiday.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /extra_holidays/1
  # DELETE /extra_holidays/1.json
  def destroy
    @extra_holiday.destroy
    respond_to do |format|
      format.html { redirect_to extra_holidays_url, notice: 'Extra holiday was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_extra_holiday
      @extra_holiday = ExtraHoliday.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def extra_holiday_params
      params.require(:extra_holiday).permit(:title, :description, :is_hourly, :is_comment_required, :is_paid, :is_as_attended)
    end
end

app/views/extra_holidays/_form.html.erb
<%= form_for(@extra_holiday) do |f| %>
  <% if @extra_holiday.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@extra_holiday.errors.count, "error") %> prohibited this extra_holiday from being saved:</h2>

      <ul>
      <% @extra_holiday.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :is_hourly %><br>
    <%= f.check_box :is_hourly %>
  </div>
  <div class="field">
    <%= f.label :is_comment_required %><br>
    <%= f.check_box :is_comment_required %>
  </div>
  <div class="field">
    <%= f.label :is_paid %><br>
    <%= f.check_box :is_paid %>
  </div>
  <div class="field">
    <%= f.label :is_as_attended %><br>
    <%= f.check_box :is_as_attended %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/extra_holidays/edit.html.erb
<h1>Editing Extra Holiday</h1>

<%= render 'form' %>

<%= link_to 'Show', @extra_holiday %> |
<%= link_to 'Back', extra_holidays_path %>

app/views/extra_holidays/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Extra Holidays</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Is hourly</th>
      <th>Is comment required</th>
      <th>Is paid</th>
      <th>Is as attended</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @extra_holidays.each do |extra_holiday| %>
      <tr>
        <td><%= extra_holiday.title %></td>
        <td><%= extra_holiday.description %></td>
        <td><%= extra_holiday.is_hourly %></td>
        <td><%= extra_holiday.is_comment_required %></td>
        <td><%= extra_holiday.is_paid %></td>
        <td><%= extra_holiday.is_as_attended %></td>
        <td><%= link_to 'Show', extra_holiday %></td>
        <td><%= link_to 'Edit', edit_extra_holiday_path(extra_holiday) %></td>
        <td><%= link_to 'Destroy', extra_holiday, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Extra holiday', new_extra_holiday_path %>

app/views/extra_holidays/new.html.erb
<h1>New Extra Holiday</h1>

<%= render 'form' %>

<%= link_to 'Back', extra_holidays_path %>

app/views/extra_holidays/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @extra_holiday.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @extra_holiday.description %>
</p>

<p>
  <strong>Is hourly:</strong>
  <%= @extra_holiday.is_hourly %>
</p>

<p>
  <strong>Is comment required:</strong>
  <%= @extra_holiday.is_comment_required %>
</p>

<p>
  <strong>Is paid:</strong>
  <%= @extra_holiday.is_paid %>
</p>

<p>
  <strong>Is as attended:</strong>
  <%= @extra_holiday.is_as_attended %>
</p>

<%= link_to 'Edit', edit_extra_holiday_path(@extra_holiday) %> |
<%= link_to 'Back', extra_holidays_path %>