config/routes.rb
Rails.application.routes.draw do

  resources :special_holidays
  resources :special_holiday_ctgrs
  resources :extra_holidays

  root 'static_pages#home'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :timecards do
    member do
      post 'workflow'
      post 'apply_all'
      post 'approve_all'
    end
  end
  get 'paid_holidays' => 'paid_holidays#index'
  resources :reports
  get 'report_download' => 'report_submissions#download'
  get 'my_reports' => 'reports#my_reports'
  resources :report_submissions do
    member do
      post 'approve'
    end
  end
  resources :users

end

app/models/report.rb
# == Schema Information
#
# Table name: reports
#
#  id               :integer          not null, primary key
#  receiver_user_id :integer
#  report_name      :string
#  beginning_date   :date
#  due_date         :date
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

class Report < ActiveRecord::Base
  has_many :report_requests, dependent: :destroy
  has_many :report_submissions, through: :report_requests

  validates :report_name, presence: true
  validates :beginning_date, presence: true
  validates :due_date, presence: true

  attr_accessor :target_user_ids

  def Report.reports_of(user_id, date = Date.today)
    Report.joins(:report_requests).where('beginning_date < ?', date)
                                  .where(report_requests: {submitter_user_id: user_id})
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
    @reports = Report.where(receiver_user_id: current_user.id)
  end

  def new
    @report = Report.new
    @target_users = User.where(id: -1)
    @untarget_users = User.where(admin: false)

    render 'edit'
  end

  def edit
    @report = Report.find(params[:id])
    @target_user_ids = @report.report_requests.pluck(:submitter_user_id)
    @target_users = User.where(id: @target_user_ids)
    @untarget_users = User.where.not(id: @target_user_ids).where(admin: false)
  end

  def create
    @report = Report.new(report_params)
    @report.receiver_user_id = current_user.id

    @target_user_ids = params[:report][:target_user_ids].split
    @target_user_ids.each do |u|
      @report.report_requests << ReportRequest.new(submitter_user_id: u.to_i)
    end

    if @report.save
      flash[:success] = "Report updated!"
      redirect_to reports_path
    else
      @target_users = User.where(id: @target_user_ids)
      @untarget_users = User.where.not(id: @target_user_ids).where(admin: false)
      render 'edit'
    end
  end

  def update
    @report = Report.find(params[:id])
    @report.attributes = report_params

    current_target_user_ids = @report.report_requests.pluck(:submitter_user_id)
    @target_user_ids = params[:report][:target_user_ids].split
    del_ids = current_target_user_ids - @target_user_ids
    add_ids = @target_user_ids - current_target_user_ids
    @report.report_requests.each do |rr|
      if del_ids.include?(rr.submitter_user_id) 
	rr.delete
      end
    end
    add_ids.each do |u|
      @report.report_requests << ReportRequest.new(submitter_user_id: u.to_i)
    end

    if @report.save
      flash[:success] = "Report updated!"
      redirect_to reports_path
    else
      @target_users = User.where(id: @target_user_ids)
      @untarget_users = User.where.not(id: @target_user_ids).where(admin: false)
      render 'edit'
    end
  end

  def destroy
    if Report.find(params[:id]).destroy
      flash[:success] = "削除しました。"
    else
      flash[:danger] = "削除に失敗しました。"
    end

    redirect_to reports_path
  end

  def my_reports
    @reports = Report.reports_of(current_user.id)
    @users = User.all
    @report_submission = ReportSubmission.new
  end

  private

    def report_params
      params.require(:report).permit(:report_name, :beginning_date, :due_date)
    end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/edit.html.erb
<% provide(:title, '提出依頼') %>
<h1>提出依頼</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@report) do |f| %>
      <% @errors = @report.errors %>
      <%= render 'shared/error_messages' %>

      <div class="form-group">
        <%= f.label :report_name, "提出物名称" %>
        <%= f.text_field :report_name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :beginning_date, "表示開始" %>
        <%= f.date_field :beginning_date, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :due_date, "提出期限" %>
        <%= f.date_field :due_date, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.hidden_field :target_user_ids, value: @target_user_ids %>
        <%= f.label :target_users do %>
	  提出対象者 <small>※提出済の人は対象外にできません</small>
	<% end %>
        <div class="form-group row">
          <div class="col-md-5">
	    <% disabled_user_ids = [] %>
	    <% @report.report_requests.each do |rr| %>
	      <% disabled_user_ids << rr.submitter_user_id if rr.report_submissions.count > 0 %>
	    <% end %>
            <%= select_tag :target_users, 
                           options_for_select(@target_users.map {|u| [u.name, u.id]}, disabled: disabled_user_ids),
                           class: 'form-control', size: 5, style: 'height: 130px;', multiple: true %>
          </div>
          <div class="col-md-2" style="padding-left: 5px;">
            <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <%= button_tag '⇨', id: 'move-right', type: 'button' %>
            <br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <%= button_tag '⇦', id: 'move-left', type: 'button' %>
          </div>
          <div class="col-md-5">
            <%= select_tag :untarget_users, options_for_select(@untarget_users.map {|u| [u.name, u.id]}), 
                            class: 'form-control', size: 5, style: 'height: 130px;', multiple: true %>
          </div>
        </div>
      </div>

      <div>
        <%= link_to "戻る", reports_path, class: "col-md-6 btn btn-default" %>
        <%= f.submit "保存", name: "save", class: "col-md-6 btn btn-info" %>
      </div>
    <% end %>
  </div>
</div>

<script type="text/javascript">
  function moveOption(event) {
    $("#" + event.data.from + " option:selected").each(function () {
      $(this).appendTo($("#" + event.data.to));
      $(this).prop("selected", false);// 選択状態の解除
    });
  }
  // 「⇨」ボタンのクリック時
  $('#move-right').on("click", {from: "target_users", to: "untarget_users"}, moveOption);

  // 「⇦」ボタンのクリック時
  $('#move-left').on("click", {from: "untarget_users", to: "target_users"}, moveOption);

  $('form').submit(function(){
    var arr = []
    var obj = $('#target_users').children();
    for (var i=0; i<obj.length; i++) {
      arr.push(obj.eq(i).val())
    }
    $('#report_target_user_ids').val(arr.join(' '))
  })
</script>

app/views/reports/index.html.erb
<% provide(:title, '提出依頼一覧') %>
<h1>提出依頼一覧</h1>

<div class="row">
  <div class="col-md-10 col-md-offset-1">
<table class="table table-bordered table-condensed">
  <thead>
    <tr align="center">
      <th class="centerized">提出物</th>
      <th class="centerized">表示開始</th>
      <th class="centerized">提出期限</th>
      <th class="centerized">対象者</th>
      <th class="centerized">未提出</th>
      <th class="centerized">提出済み</th>
      <th class="centerized"></th>
    </tr>
  </thead>
  <tbody>
    <% @reports.each do |r| %>
      <tr align="center">
        <th class=""><%= r.report_name %></th>
        <th class="centerized"><%= r.beginning_date.to_s(:y_slash_m_slash_d) %></th>
        <th class="centerized"><%= r.due_date.to_s(:y_slash_m_slash_d) %></th>
        <th class="centerized"><%= r.report_requests.count %>名</th>
        <th class="centerized"><%= r.report_requests.count - r.report_submissions.count %>名</th>
        <th class="centerized">
	  <% submitted_count = 0 %>
	  <% r.report_requests.each do |rr|%>
	    <% submitted_count += 1 if rr.report_submissions.count > 0 %>
	  <% end %>
	  <%= submitted_count %>名
	</th>
        <th class="centerized">
          <%= link_to "", edit_report_path(r.id), class: "glyphicon glyphicon-pencil", title: "編集" %>
          &nbsp;
          <%= link_to "", report_submissions_path(r_id: r.id), 
	                    class: "glyphicon glyphicon-th-list", title: "提出状況" %>
          &nbsp;
	  <% if submitted_count > 0 %>
	    <span class="glyphicon glyphicon-remove" style="color:silver"></span>
	  <% else %>
            <%= link_to "", r, method: :delete, data: {confirm: '削除しますか？'},
	                    class: "glyphicon glyphicon-remove", title: "削除" %>
	  <% end %>
        </th>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to "新規", new_report_path(0), class: "col-md-12 btn btn-info" %>
</div>
</div>

app/views/reports/my_reports.html.erb
<% provide(:title, '提出物一覧') %>
<h1>提出物一覧</h1>

<div class="row">
  <div class="col-md-10 col-md-offset-1">
<table class="table table-bordered table-condensed">
  <thead>
    <tr align="center">
      <th class="centerized">提出物</th>
      <th class="centerized">提出先</th>
      <th class="centerized">提出期限</th>
      <th class="centerized">ステータス</th>
      <th class="centerized col-md-5">ファイル</th>
    </tr>
  </thead>
  <tbody>
    <% @reports.each do |r| %>
      <% rr = r.report_requests.find_by(submitter_user_id: current_user.id) %>
      <tr align="center">
        <th class=""><%= r.report_name %></th>
        <th class="centerized"><%= @users.find(r.receiver_user_id).name %></th>
        <th class="centerized"><%= r.due_date.to_s(:y_slash_m_slash_d) %></th>
        <th class="centerized">
	  <% if rr.approved %>
	    <span style="color:silver;">承認済</span>
	  <% elsif rr.report_submissions.count == 0 %>
	    <span style="color:red;">未提出</span>
	  <% else %>
	    <span style="color:blue;">提出済み</span>
	  <% end %>
	</th>
        <th class="">
	  <% rr.report_submissions.each_with_index do |rs, i|%>
	    <%= '<br>'.html_safe if i != 0 %>
	    <%= rs.file_name %>
	    <% unless rr.approved %>
              <%= link_to "削除", report_submission_path(rs.id), method: :delete, 
	                   data: {confirm: '削除しますか？'}, class: "btn btn-default btn-xs" %>
	    <% end %>
	  <% end%>
	    <% unless rr.approved %>
	    <%= form_for @report_submission, html: {class: 'form-horizontal'} do |f| %>
              <%= f.hidden_field :report_request_id, value: rr.id %>
	      <div class="input-group">
	        <%= f.file_field :upload_file, class: 'form-control upload-file' %>
	        <div class="input-group-btn">
	          <%= f.submit "提出", class: 'form-control btn btn-default btn-xs' %>
	        </div>
	      </div>
	    <% end %>
	  <% end %>
        </th>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>