config/routes.rb
Rails.application.routes.draw do

  resources :special_holidays
  resources :special_holiday_ctgrs
  resources :extra_holidays

  root 'static_pages#home'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :timecards do
    member do
      post 'workflow'
      post 'apply_all'
      post 'approve_all'
    end
  end
  get 'paid_holidays' => 'paid_holidays#index'
  resources :reports
  get 'report_download' => 'report_submissions#download'
  get 'my_reports' => 'reports#my_reports'
  resources :report_submissions do
    member do
      post 'approve'
    end
  end
  resources :users

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
     WORKAHOLIC is proudly powered by 
     <a href="http://www.linkage.jp.net/"><span style="color: orange;">L</span>inkage, Inc.</a>
     ©<%= Date.today.year.to_s %>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "WORKAHOLIC", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
	      勤怠<b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "勤怠一覧", root_path %></li>
              <li><%= link_to "有給休暇照会", paid_holidays_path %></li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
	      提出物<b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li>
	        <%= link_to my_reports_path do %>
		  提出物一覧
		  <% unsubmitted_count = ReportRequest.unsubmitted_count(current_user.id) %>
		  <% if unsubmitted_count > 0%>
		    <span class="badge pull-right"><%= unsubmitted_count %></span>
		  <% end %>
		<% end %>
	      </li>
              <li><%= link_to "提出依頼管理", reports_path %></li>
            </ul>
          </li>
	  <% if current_user.admin %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
	        人事管理*<b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "社員管理*", users_path %></li>
                <li><%= link_to "有給管理*", '#' %></li>
                <li><%= link_to "臨時休暇管理", extra_holidays_path %></li>
                <li><%= link_to "特別休暇管理", special_holidays_path %></li>
              </ul>
            </li>
	  <% else %>
            <li><%= link_to "社員一覧", users_path %></li>
	  <% end %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
	      <%= current_user.name %><b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <!-- <li><%= link_to "プロフィール", current_user %></li> -->
              <li><%= link_to "設定", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "ログアウト", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>